name: PEP8 Check

on:
  push:
    branches:
      - main
      - "**"
  pull_request:

jobs:
  pycodestyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle black

      - name: Run pycodestyle
        run: pycodestyle --count --statistics --exclude=venv .

      - name: Run black check
        run: black --check .